package com.m4.contacts.selenium;
// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import java.util.HashMap;
import java.util.Map;

public class TestSeleniumIDE {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1194, 1146));
    driver.findElement(By.linkText("ADD CONTACT")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Alma");
    driver.findElement(By.id("lastName")).sendKeys("Alma");
    driver.findElement(By.id("phoneNumber")).sendKeys("0123456789");
    driver.findElement(By.cssSelector(".button-form")).click();
    driver.findElement(By.linkText("CONTACT LIST")).click();
    {
      WebElement element = driver.findElement(By.linkText("CONTACT LIST"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("SEARCH CONTACT")).click();
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Alma");
    driver.findElement(By.cssSelector(".button-form")).click();
    driver.findElement(By.cssSelector(".link:nth-child(2) > button")).click();
    driver.findElement(By.id("contactId")).click();
    driver.findElement(By.id("contactId")).sendKeys("6");
    driver.findElement(By.cssSelector(".button-form")).click();
  }
}
